### ISSUE TITLE
How to check if an episode is actually new

### ISSUE THREAD

**Issue by chstem** [mi-verschwoerer/mi-announce-bot#3]
We need some way to determine whether a new episode is actually new. Possible approaches are:

1. check if older than 1 hour (stateless)
1. ~~check if the bot already posted a message to the telegram group since the last episode has been released (stateless)~~
1. save in some local file (stateful)

Problems:
1. If the bot checks more often then the defined time difference, it will annouce the episode multiple times. Also, if the Bot is temporarily offline for some reason, it may miss an episode.
1. I don't know yet whether the Telegram BOT API allows access to the chat history or previously send messages. I will check that later.

**Comment by CryptKid** [comment]
I'd go for some stateless approach since that makes deployment a lot easier (specifically if using containerisation)

**Comment by madonius** [comment]
There is also the in-between. We could hold a state for the last hour (if that is our time frame) and report on that. Thus we would be reporting multiple times only if the bot happens to die within an hour of a release.

Finally, I would propose going for a cron-like deployment, as this is easier to be deployed.

**Comment by chstem** [comment]
I would also deploy it with crontab or a systemd timer. But if this periodically starts the bot, how do you want to hold the temporary state? You could store a file in /tmp ...

**Comment by chstem** [comment]
Seems like option 2 is not possible with the bot API.

**Comment by madonius** [comment]
So let's do the temporary state thingy, right?

**Comment by chstem** [comment]
After a "short" trial period, stateless seems to work just fine.
